version: '3'

services:
  brain:
    build: ./cloth-brain
    command: npm start
    volumes:
      - ./cloth-brain:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
      image: mongo
      ports:
        - "27017:27017"